version: '3.7'
services:
  node:
    build:
      context: ./
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 3333:3333
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379

networks:
  app_mehdi_net:
    driver: bridge
