version: '3.7'
services:
  node:
    build:
      context: ./
    networks:
      - app_mehdi_net
    ports:
      - 3331:3333
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379
    networks:
      - app_mehdi_net

networks:
  app_mehdi_net:
    driver: bridge
